import type {Metadata} from "next";
import "./globals.css";
import ReduxProvider from "@/app/Provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ru">
        <body>
        <ReduxProvider>
            {children}
        </ReduxProvider>

        </body>
        </html>
    );
}
