name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repo files for debug
        run: |
          pwd
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Run unit tests (Jest)
        run: pnpm test:ci

      - name: Build project
        run: pnpm build

      - name: Run Cypress (e2e)
        uses: cypress-io/github-action@v6
        with:
          start: pnpm dev
          wait-on: 'http://localhost:3000'
